# These are supported funding model platforms

github: [sistematico]
patreon: sistematico
buy_me_a_coffee: sistematico
open_collective: sistematico
ko_fi: sistematico01
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: sistematico
issuehunt: # Replace with a single IssueHunt username
otechie: # Replace with a single Otechie username
custom: ["https://pag.ae/bfxkQW"]