version: '3'

services:
  app:
    image: dh1011/start-ichi:latest
    ports:
      - "5000:5000"
    volumes:
      - data:/app/data
    environment:
      - FLASK_ENV=production
    restart: unless-stopped

volumes:
  data: