name: Deploy GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v4

      - name: Upload arquivo de build
        uses: actions/upload-pages-artifact@v3
        with:
          path: './'

      - name: Deploy para o GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4